package model;

/**
 * Product.java
 * ---------------------------------------------------------
 * Team Member 1 - Core Domain Model
 *
 * A simple data class (POJO) that represents one row from the
 * input CSV file. Each Product knows how to calculate its own
 * total revenue (quantitySold * unitPrice).
 * ---------------------------------------------------------
 */
public class Product {

    private final String productId;
    private final String productName;
    private final String category;
    private final int quantitySold;
    private final double unitPrice;

    public Product(String productId, String productName, String category,
                    int quantitySold, double unitPrice) {
        this.productId = productId;
        this.productName = productName;
        this.category = category;
        this.quantitySold = quantitySold;
        this.unitPrice = unitPrice;
    }

    public String getProductId() {
        return productId;
    }

    public String getProductName() {
        return productName;
    }

    public String getCategory() {
        return category;
    }

    public int getQuantitySold() {
        return quantitySold;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    /**
     * Calculates the total revenue generated by this single product.
     * Formula: quantity_sold * unit_price
     */
    public double getTotalRevenue() {
        return quantitySold * unitPrice;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id='" + productId + '\'' +
                ", name='" + productName + '\'' +
                ", category='" + category + '\'' +
                ", qty=" + quantitySold +
                ", unitPrice=" + unitPrice +
                '}';
    }
}
